version: '3.9'
services:
  symfony:
    depends_on:
      - mysql
    volumes:
      - ./symfony:/var/www/html/symfony.docker
      - ./src/apache2/hosts:/etc/apache2/sites-enabled
      - ./tmp:/tmp
    build: .
    container_name: symfony
    ports:
      - 8081:80
    links:
      - mysql
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3300:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


