version: '3.9'
services:
  ${LOCAL_HOST_NAME}:
    depends_on:
      - ${DB_LOCAL_HOST_NAME}
    volumes:
      - ./symfony:/var/www/html/symfony.docker
      - ./src/apache2/hosts:/etc/apache2/sites-enabled
      - ./tmp:/tmp
    build: .
    container_name: ${LOCAL_HOST_NAME}
    ports:
      - ${SITE_LOCAL_PORT}:80
    links:
      - ${DB_LOCAL_HOST_NAME}
    restart: always
  ${ADMINER_LOCAL_HOST_NAME}:
    image: adminer
    container_name: ${ADMINER_LOCAL_HOST_NAME}
    restart: always
    ports:
      - ${ADMINER_LOCAL_PORT}:8080
  ${DB_LOCAL_HOST_NAME}:
    image: mysql:8.0
    restart: always
    container_name: ${DB_LOCAL_HOST_NAME}
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - ${DB_LOCAL_HOST_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


