version: '3.9'
services:
  site:
    depends_on:
      - db
    volumes:
      - ./symf.doc:/var/www/html/symf.doc
      - ./src/apache2/hosts:/etc/apache2/sites-enabled
      - ./tmp:/tmp
    build: .
    container_name: symf.doc
    ports:
      - 8080:80
    links:
      - db
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3300:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: symf
      MYSQL_PASSWORD: symf
      MYSQL_DATABASE: symf
      MYSQL_ROOT_PASSWORD: 11111111



